export const departamentos = [
  {
    departamento: 'Nueva Segovia',
    municipios: [
      'Jalapa',
      'Murra',
      'El Jícaro',
      'San Fernando',
      'Mozonte',
      'Dipilto',
      'Macuelizo',
      'Santa María',
      'Ocotal',
      'Ciudad Antigua',
      'Quilalí',
      'Wiwilí de Nueva Segovia',
    ],
  },
  {
    departamento: 'Jinotega',
    municipios: [
      'Wiwilí',
      'Cuá-Bocay',
      'San Rafael del Norte',
      'San Sebastián de Yalí',
      'La Concordia',
      'Jinotega',
    ],
  },
  {
    departamento: 'Madriz',
    municipios: [
      'Somoto',
      'Totogalpa',
      'Telpaneca',
      'San Juan de Río Coco',
      'Palacagüina',
      'Yalagüina',
      'San Lucas',
      'Las Sabanas',
      'San José de Cusmapa',
    ],
  },
  {
    departamento: 'Estelí',
    municipios: [
      'Pueblo Nuevo',
      'Condega',
      'Estelí',
      'San Juan de Limay',
      'La Trinidad',
      'San Nicolás',
    ],
  },
  {
    departamento: 'Chinandega',
    municipios: [
      'San Pedro del Norte',
      'San Francisco del Norte',
      'Cinco Pinos',
      'Santo Tomás del Norte',
      'El Viejo',
      'Pto. Morazán',
      'Somotillo',
      'Villanueva',
      'Chinandega',
      'El Realejo',
      'Corinto',
      'Chichigalpa',
      'Posoltega',
    ],
  },
  {
    departamento: 'León',
    municipios: [
      'Achuapa',
      'El Sauce',
      'Santa Rosa del Peñón',
      'El Jicaral',
      'Larreynaga',
      'Telica',
      'Quezalguaque',
      'León',
      'La Paz Centro',
      'Nagarote',
    ],
  },
  {
    departamento: 'Matagalpa',
    municipios: [
      'Rancho Grande',
      'Río Blanco',
      'El Tuma - La Dalia',
      'San Isidro',
      'Sébaco',
      'Matagalpa',
      'San Ramón',
      'Matiguás',
      'Muy Muy',
      'Esquipulas',
      'San Dionisio',
      'Terrabona',
      'Ciudad Darío',
    ],
  },
  {
    departamento: 'Boaco',
    municipios: [
      'San José de los Remates',
      'Boaco',
      'Camoapa',
      'Santa Lucía',
      'Teustepe',
      'San Lorenzo',
    ],
  },
  {
    departamento: 'Managua',
    municipios: [
      'San Francisco Libre',
      'Tipitapa',
      'Mateare',
      'Villa Carlos Fonseca',
      'Francisco Javier C.Sandino',
      'Managua',
      'Ticuantepe',
      'El Crucero',
      'San Rafael del Sur',
    ],
  },
  {
    departamento: 'Masaya',
    municipios: [
      'Nindirí',
      'Masatepe',
      'Masaya',
      'Tisma',
      'La Concepción',
      'Nandasmo',
      'Catarina',
      'San Juan de Oriente',
      'Niquinohomo',
    ],
  },
  {
    departamento: 'Chontales',
    municipios: [
      'Comalapa',
      'San Francisco Cuapa',
      'Juigalpa',
      'La Libertad',
      'Santo Domingo',
      'San Pedro de Lóvago',
      'Acoyapa',
      'Villa Sandino',
      'El Coral',
    ],
  },
  {
    departamento: 'Granada',
    municipios: ['Diriá', 'Diriomo', 'Granada', 'Nandaime'],
  },
  {
    departamento: 'Carazo',
    municipios: [
      'San Marcos',
      'Jinotepe',
      'Dolores',
      'Diriamba',
      'El Rosario',
      'La Paz de Carazo',
      'Santa Teresa',
      'La Conquista',
    ],
  },
  {
    departamento: 'Rivas',
    municipios: [
      'Tola',
      'Belén',
      'Potosí',
      'Buenos Aires',
      'Moyogalpa',
      'Altagracia',
      'San Jorge',
      'Rivas',
      'San Juan del Sur',
      'Cárdenas',
    ],
  },
  {
    departamento: 'Rio San Juan',
    municipios: [
      'Morrito',
      'El Almendro',
      'San Miguelito',
      'San Carlos',
      'El Castillo',
      'San Juan del Norte',
    ],
  },
  {
    departamento: 'Atlántico Norte',
    municipios: [
      'Waspán',
      'Puerto Cabezas',
      'Rosita',
      'Bonanza',
      'Waslala',
      'Siuna',
      'Prinzapolka',
    ],
  },
  {
    departamento: 'Atlántico Sur',
    municipios: [
      'Paiwas',
      'La Cruz de Río Grande',
      'Desembocadura de Río Grande',
      'Laguna de Perlas',
      'El Tortuguero',
      'Rama',
      'El Ayote',
      'Muelle de los Bueyes',
      'Kukra Hill',
      'Corn Island',
      'Bluefields',
      'Nueva Guinea',
    ],
  },
];
